# Generated by Django 5.2.3 on 2025-06-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікується'), ('confirmed', 'Підтверджено'), ('canceled', 'Відмінено')], default='pending', max_length=10),
        ),
    ]
